update

diff --git a/chrome b/chrome
--- a/chrome
+++ b/chrome
@@ -3,15 +3,38 @@
 verb="$1"
 shift
 
+function join_by {
+	local d=${1-} f=${2-}
+	if shift 2; then
+		printf %s "$f" "${@/#/$d}"
+	fi
+}
+
 case "$verb" in
-pull) ;;
+pull)
+	if ! dir="$(./.zit/bin/chrome_tabs_to_files)"; then
+		echo "failed to pull chrome tabs" >&1
+		exit 1
+	fi
+
+	#TODO support no tabs
+	zit new -edit=false -dedupe -etiketten "$(join_by ',' "$@")" $dir/*
+
+	if ! ./.zit/bin/chrome_close_all; then
+		echo "failed to close all chrome tabs" >&1
+		exit 1
+	fi
+
+	echo "deleting tabs saved to '$dir'" >&2
+	rm -r "$dir"
+	;;
 
 push)
 	zit cat-objekte -type akte !toml-bookmark "$@" |
 		tomlq -r '.[].url' |
-    tr '\n' '\0' |
+		tr '\n' '\0' |
 		xargs -0 open --new -a 'Google Chrome' --args --new-window
-	 ;;
+	;;
 
 *) ;;
 
diff --git a/web-save-all b/web-save-all
--- a/web-save-all
+++ b/web-save-all
@@ -8,65 +8,19 @@ date_tag() (
 	echo "zz-inbox-$(date)"
 )
 
-get_all_urls() (
-	~/Eng/Alfred/Alfred.alfredpreferences/workflows/zit/chrome_tabs.js |
-		jq -cr '.[] | .'
-)
-
-close_all() (
-	~/Eng/Alfred/Alfred.alfredpreferences/workflows/zit/close_chrome_tabs.js
-)
-
-get_url_components() (
-	php -r 'while($f = fgets(STDIN)){ echo json_encode(array_merge(parse_url($f), ["url"=>trim($f)])) . "\n"; }'
-)
-
-get_host() (
-	get_url_components |
-		jq -r '.host | if (. | tostring | startswith("www")) then .[4:] else . end | tostring | split(".") | reverse | join("-")'
-)
-
-inbox_tag="$(date_tag)"
-
-files=()
-
-dir="$(mktemp -d)"
-echo "saving tabs to '$dir'" >&2
-
-while read -r; do
-	url="$(echo "$REPLY" | jq -r .url)"
-
-	case "$url" in
-	https://asana.zoom.us/j/*)
-		continue
-		;;
-
-	*) ;;
-
-	esac
-
-	title="$(echo "$REPLY" | jq -r .title)"
-	host="$(echo "$url" | get_host)"
-	url_encoded="$(echo "$REPLY" | jq -r '.url | @uri')"
-	file_name="$dir/$(echo "$url" | sha1sum | cut -d' ' -f1)"
-
-	{
-		echo ---
-		echo "# $title"
-		echo "- zz-site-$host"
-		echo "! toml-bookmark"
-		echo ---
-		echo
-		echo "url = \"$url\""
-	} >"$file_name"
-
-	files+=("$file_name")
-done < <(get_all_urls)
+if ! dir="$(./.zit/bin/chrome_tabs_to_files)"; then
+	echo "failed to pull chrome tabs" >&1
+	exit 1
+fi
 
 #TODO support no tabs
-zit new -edit=false -dedupe -etiketten "$inbox_tag" "${files[@]}"
+zit new -edit=false -dedupe -etiketten "$inbox_tag" $dir/*
 # zit organize -group-by zz-site "$inbox_tag" !toml-bookmark
 
+if ! ./.zit/bin/chrome_close_all; then
+	echo "failed to close all chrome tabs" >&1
+	exit 1
+fi
+
 echo "deleting tabs saved to '$dir'" >&2
-# rm -r "$dir"
-close_all
+rm -r "$dir"
